export const FETCHING_PEOPLE_REQUEST = 'FETCHING_PEOPLE_REQUEST'
export const FETCHING_PEOPLE_SUCCESS = 'FETCHING_PEOPLE_SUCCESS'
export const FETCHING_PEOPLE_ERROR = 'FETCHING_PEOPLE_ERROR'

export const FETCHING_PERSON_REQUEST = 'FETCHING_PERSON_REQUEST'
export const FETCHING_PERSON_SUCCESS = 'FETCHING_PERSON_SUCCESS'
export const FETCHING_PERSON_ERROR = 'FETCHING_PERSON_ERROR'
